FROM nginx:1.21-alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx/nginx.conf /etc/nginx/conf.d
# This allows access log redirection to stdout/stderr
RUN ln -sf /dev/stdout /var/log/nginx/access.log

EXPOSE 80 443
